<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <SatelliteResourceLanguages>-</SatelliteResourceLanguages>
    <PublishDocumentationFile>false</PublishDocumentationFile>
    <CopyDocumentationFilesFromPackages>false</CopyDocumentationFilesFromPackages>
    <CopyDebugSymbolFilesFromPackages>false</CopyDebugSymbolFilesFromPackages>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.22" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="efpt.config.json" CopyToOutputDirectory="Never" CopyToPublishDirectory="Never" />
    <Content Update="appsettings.Development.json" CopyToPublishDirectory="Never" />
  </ItemGroup>

</Project>
